apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: all
requires:
  - path: ./backend/environments/skaffold.yaml
  - path: ./frontend/environments/skaffold.yaml
  - path: ./gateway/environments/skaffold.yaml