apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-flask-k8s-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-flask-k8s-web
  template:
    metadata:
      labels:
        app: next-flask-k8s-web
    spec:
      containers:
      - name: next-flask-k8s-web
        image: next-flask-k8s-web:latest  # 先ほどビルドしたDockerイメージ
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
          - name: KONG_GATEWAY_URL
            value: "http://kong-gateway-service.default.svc.cluster.local:8000"
        readinessProbe:  # コンテナの準備状態を確認
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:  # コンテナが正常かどうかのヘルスチェック
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20