apiVersion: v1
kind: Service
metadata:
  name: next-flask-k8s-web-service
spec:
  selector:
    app: next-flask-k8s-web
  ports:
    - protocol: TCP
      port: 3000  # 外部アクセス用のポート
      targetPort: 3000  # コンテナ内のポート
  type: ClusterIP
