apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: next-flask-k8s-api
build:
  artifacts:
    - image: next-flask-k8s-api
      context: ../
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: next-flask-k8s-api
        chartPath: app/helm/deployment
profiles:
  - name: local
    # activation:
    #   - command: dev
    patches:
      - op: remove
        path: /build
      - op: remove
        path: /manifests/helm/releases/0
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: mongo-db
          chartPath: ./db/helm/deployment
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: mongo-db-cm
          chartPath: ./db/helm/config-map
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: redis
          chartPath: ./redis/helm/deployment

  - name: integration
    patches:
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: mongo-db
          chartPath: ./db/helm/deployment
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: mongo-db-cm
          chartPath: ./db/helm/config-map
      - op: add
        path: /manifests/helm/releases/-
        value:
          name: redis
          chartPath: ./redis/helm/deployment