apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-flask-k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-flask-k8s-api
  template:
    metadata:
      labels:
        app: next-flask-k8s-api
    spec:
      containers:
      - name: next-flask-k8s-api
        image: next-flask-k8s-api:latest  # 先ほどビルドしたDockerイメージ
        ports:
        - containerPort: 5600
        resources:
          requests:
            memory: "512Mi"  # 最低512MBのメモリを要求
            cpu: "500m"      # 最低0.5CPUを要求
          limits:
            memory: "1Gi"    # 最大1GBのメモリを設定
            cpu: "1"         # 最大1CPUを設定
        env:
          - name: MONGO_URI
            value: "mongodb://root:root@mongo-service.default.svc.cluster.local:27017/mydatabase?authSource=admin"
          - name: REDIS_URI
            value: "redis-service.default.svc.cluster.local"