apiVersion: v1
kind: Service
metadata:
  name: next-flask-k8s-api-service
spec:
  selector:
    app: next-flask-k8s-api
  ports:
    - protocol: TCP
      port: 5600  # 外部アクセス用のポート
      targetPort: 5600  # コンテナ内のポート
  type: ClusterIP  # または ClusterIP
