apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yaml: |
    _format_version: "1.1"  # または適切なバージョンを指定
    services:
      - name: next-flask-k8s-api
        url: http://next-flask-k8s-api-service.default.svc.cluster.local:5600/v1
        routes:
          - name: api-route
            paths:
              - /api/*
            plugins:
              - name: cors
                config:
                  methods: 
                    - GET
                    - POST
                    - OPTIONS
                  headers: 
                    - Accept
                    - Authorization
                    - Content-Type
                  origins: 
                    - http://localhost:3000  # 許可するオリジン
                  exposed_headers: 
                    - X-Custom-Header  # 必要な場合
                  max_age: 3600
