apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest  # 公式イメージを指定
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_DECLARATIVE_CONFIG
              value: /etc/kong/kong.yaml  # ConfigMapからの設定ファイルパス
          volumeMounts:
            - name: kong-config-volume
              mountPath: /etc/kong
      volumes:
        - name: kong-config-volume
          configMap:
            name: kong-config
