apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  selector:
    app: kong
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000  # Kongのプロキシポート
    - name: admin
      port: 8001
      targetPort: 8001  # Kongの管理APIポート
  type: ClusterIP  # クラスタ内部でのみアクセス可能