name: Deploy Next.js to Amplify

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::932046244732:role/GithubDeployRole
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: |
          cd frontend/app
          npm ci

      - name: Build Next.js app
        run: |
          cd frontend/app
          npm run build

      - name: Start Amplify deployment
        run: |
          aws amplify start-deployment \
            --app-id dq4btzthj3t72 \
            --branch-name main \
            --source-dir frontend/app/.next
